In [1]:
import pandas as pd
from pathlib import Path

print("Student Performance Prediction System")
print("Day 35: Final Dataset Validation")

Student Performance Prediction System
Day 35: Final Dataset Validation

In [4]:
from pathlib import Path
import pandas as pd

# Eita change kara - jouthi tuma notebook chalucha
root = Path(r"C:\Users\Bagmita\OneDrive\Desktop\Project")
# ba direct current folder
# root = Path.cwd()

print("Khojuthiba jaga:", root)

matches = list(root.rglob("day34*.csv"))
print("day34 re mili thiba file:", matches)

if matches:
    df = pd.read_csv(matches[0])
    print("File found:", matches[0])
    print(df.shape)
    display(df.head())
else:
    print("OneDrive folder re bhi nahi. Day 34 Cell 11 run kariba darkar.")

Khojuthiba jaga: C:\Users\Bagmita\OneDrive\Desktop\Project
day34 re mili thiba file: [WindowsPath('C:/Users/Bagmita/OneDrive/Desktop/Project/day34_dataset_quality_report.csv'), WindowsPath('C:/Users/Bagmita/OneDrive/Desktop/Project/day34_final_student_features.csv'), WindowsPath('C:/Users/Bagmita/OneDrive/Desktop/Project/day34_missing_value_report.csv')]
File found: C:\Users\Bagmita\OneDrive\Desktop\Project\day34_dataset_quality_report.csv
(4, 8)

,Feature,Data Type,Total Rows,Missing Values,Unique Values,Minimum,Maximum,Mean
0,study_hours,float64,3,0,3,4.20,6.40,5.13
1,attendance,float64,3,0,3,85.50,91.00,87.83
2,previous_score,float64,3,0,3,37.80,57.60,46.20
3,assignments_completed,float64,3,0,3,8.51,8.82,8.68

In [5]:
print("Missing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:\n", df.dtypes)

Missing values:
 Feature           0
Data Type         0
Total Rows        0
Missing Values    0
Unique Values     0
Minimum           0
Maximum           0
Mean              0
dtype: int64

Duplicate rows: 0

Data types:
 Feature               str
Data Type             str
Total Rows          int64
Missing Values      int64
Unique Values       int64
Minimum           float64
Maximum           float64
Mean              float64
dtype: object

In [7]:
print("Actual columns in file:")
print(df.columns.tolist())

# Jadi scaling heichi, available features dekhaba
# Case-insensitive check
for col in df.columns:
    print(col)

Actual columns in file:
['Feature', 'Data Type', 'Total Rows', 'Missing Values', 'Unique Values', 'Minimum', 'Maximum', 'Mean']
Feature
Data Type
Total Rows
Missing Values
Unique Values
Minimum
Maximum
Mean

In [8]:
output = "day35_validated_student_features.csv"

df.to_csv(output, index=False)

print("Dataset saved:", output)
print("Shape:", df.shape)

Dataset saved: day35_validated_student_features.csv
Shape: (4, 8)

In [9]:
from pathlib import Path
import pandas as pd

file = Path("day35_validated_student_features.csv")

if file.exists():
    check_df = pd.read_csv(file)
    print("Dataset verified!")
    print("Shape:", check_df.shape)
    display(check_df.head())
else:
    print("File not found. Run Cell 5 again.")

Dataset verified!
Shape: (4, 8)

,Feature,Data Type,Total Rows,Missing Values,Unique Values,Minimum,Maximum,Mean
0,study_hours,float64,3,0,3,4.20,6.40,5.13
1,attendance,float64,3,0,3,85.50,91.00,87.83
2,previous_score,float64,3,0,3,37.80,57.60,46.20
3,assignments_completed,float64,3,0,3,8.51,8.82,8.68

In [10]:
print("Project: Student Performance Prediction System")
print("Day: 35")
print("Total Records:", len(df))
print("Total Features:", len(df.columns))
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Day 35 Validation Completed!")

Project: Student Performance Prediction System
Day: 35
Total Records: 4
Total Features: 8
Missing Values: 0
Duplicate Rows: 0
Day 35 Validation Completed!

In [11]:
report = pd.DataFrame({
    "Metric": ["Total Records", "Total Features", "Missing Values", "Duplicate Rows"],
    "Value": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

report.to_csv("day35_validation_report.csv", index=False)

print("Validation report saved successfully!")
display(report)

Validation report saved successfully!

           Metric  Value
0   Total Records      4
1  Total Features      8
2  Missing Values      0
3  Duplicate Rows      0