In [1]:
import pandas as pd
from pathlib import Path

print("Student Performance Prediction System")
print("Day 36: Model Readiness Check")

Student Performance Prediction System
Day 36: Model Readiness Check

In [3]:
from pathlib import Path
import pandas as pd

# FIX - thik path
root = Path(r"C:\Users\Bagmita\OneDrive\Desktop\Project")
# ba jouthi notebook achi seithi khojiba
# root = Path.cwd()

files = list(root.rglob("day35_validated_student_features.csv"))

print("Khojuthiba jaga:", root)
print("Mili thiba files:", files)

if files:
    df = pd.read_csv(files[0])
    print("Dataset loaded:", files[0])
    print("Dataset shape:", df.shape)
    display(df.head())
else:
    print("Dataset not found. Day 35 CSV file check kara.")
    # sabu csv dekha
    print(list(root.rglob("*.csv"))[-5:])

Khojuthiba jaga: C:\Users\Bagmita\OneDrive\Desktop\Project
Mili thiba files: [WindowsPath('C:/Users/Bagmita/OneDrive/Desktop/Project/day35_validated_student_features.csv')]
Dataset loaded: C:\Users\Bagmita\OneDrive\Desktop\Project\day35_validated_student_features.csv
Dataset shape: (4, 8)

,Feature,Data Type,Total Rows,Missing Values,Unique Values,Minimum,Maximum,Mean
0,study_hours,float64,3,0,3,4.20,6.40,5.13
1,attendance,float64,3,0,3,85.50,91.00,87.83
2,previous_score,float64,3,0,3,37.80,57.60,46.20
3,assignments_completed,float64,3,0,3,8.51,8.82,8.68

In [4]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Missing values: 0
Duplicate rows: 0
Rows: 4
Columns: 8

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nActual column names in your file:")
for c in df.columns.tolist():
    print("-", c)

Rows: 4
Columns: 8

Actual column names in your file:
- Feature
- Data Type
- Total Rows
- Missing Values
- Unique Values
- Minimum
- Maximum
- Mean

In [9]:
from pathlib import Path
import pandas as pd

root = Path(r"C:\Users\Bagmita\OneDrive\Desktop\Project")

# 1. Sabu csv dekha
print("Sabuthu badi file kana?")
for f in root.rglob("*.csv"):
    try:
        r = pd.read_csv(f).shape[0]
        print(f.name, "->", r, "rows")
    except:
        pass

# 2. Thik dataset load kara - Day 34 wala final features
files = list(root.rglob("day34_final_student_features.csv"))
if not files:
    files = list(root.rglob("day35_final_dataset*.csv"))
if not files:
    files = list(root.rglob("day35_final_dataset*.csv"))

print("\nLoading:", files[0])
df = pd.read_csv(files[0])
print(df.shape)
print(df.columns.tolist())
display(df.head())

Sabuthu badi file kana?
day18_model_evaluation_report.csv -> 4 rows
day19_model_comparison_report.csv -> 2 rows
day20_student_performance_report.csv -> 3 rows
day21_student_performance_classification_report.csv -> 15 rows
day22_model_evaluation_report.csv -> 5 rows
day22_prediction_results.csv -> 5 rows
day22_project_summary.csv -> 9 rows
day23_student_performance_summary.csv -> 7 rows
day24_dataset_quality_report.csv -> 9 rows
day24_student_performance_summary.csv -> 4 rows
day25_correlation_matrix.csv -> 4 rows
day25_dataset_quality.csv -> 7 rows
day25_prediction_summary.csv -> 7 rows
day26_correlation_matrix.csv -> 2 rows
day26_dataset_quality_report.csv -> 2 rows
day26_student_performance_summary.csv -> 2 rows
day27_correlation_matrix.csv -> 3 rows
day27_dataset_quality_report.csv -> 3 rows
day27_student_performance_summary.csv -> 7 rows
day28_cleaned_student_features.csv -> 3 rows
day29_validated_student_features.csv -> 3 rows
day30_scaled_student_features.csv -> 3 rows
day32_outlier_summary.csv -> 4 rows
day33_engineered_student_features.csv -> 3 rows
day33_feature_correlation_matrix.csv -> 7 rows
day33_feature_selection_report.csv -> 7 rows
day34_dataset_quality_report.csv -> 4 rows
day34_final_student_features.csv -> 3 rows
day34_missing_value_report.csv -> 4 rows
day35_validated_student_features.csv -> 4 rows
day35_validation_report.csv -> 4 rows
student_performance_report.csv -> 10 rows

Loading: C:\Users\Bagmita\OneDrive\Desktop\Project\day34_final_student_features.csv
(3, 4)
['study_hours', 'attendance', 'previous_score', 'assignments_completed']

   study_hours  attendance  previous_score  assignments_completed
0          6.4        91.0            57.6                   8.71
1          4.2        85.5            37.8                   8.82
2          4.8        87.0            43.2                   8.51

In [10]:
required = [
    "study_hours",
    "attendance",
    "previous_score",
    "assignments_completed"
]

missing = [col for col in required if col not in df.columns]

if not missing:
    print("All required features are available!")
else:
    print("Missing features:", missing)

All required features are available!

In [11]:
if all(col in df.columns for col in required):
    display(df[required].describe().T)
else:
    print("Required features check.")

,count,mean,std,min,25%,50%,75%,max
study_hours,3.0,5.133333,1.137248,4.20,4.50,4.80,5.600,6.40
attendance,3.0,87.833333,2.843120,85.50,86.25,87.00,89.000,91.00
previous_score,3.0,46.200000,10.235233,37.80,40.50,43.20,50.400,57.60
assignments_completed,3.0,8.680000,0.157162,8.51,8.61,8.71,8.765,8.82

In [12]:
report = pd.DataFrame({
    "Check": [
        "Dataset Loaded",
        "Required Features Available",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Result": [
        not df.empty,
        all(col in df.columns for col in required),
        int(df.isnull().sum().sum()),
        int(df.duplicated().sum())
    ]
})

report.to_csv("day36_model_readiness_report.csv", index=False)
display(report)

print("Day 36 report saved successfully!")

                         Check Result
0               Dataset Loaded   True
1  Required Features Available   True
2               Missing Values      0
3               Duplicate Rows      0

Day 36 report saved successfully!

In [13]:
output = "day36_model_ready_dataset.csv"

df.to_csv(output, index=False)

print("Dataset saved:", output)
print("Final shape:", df.shape)
print("Day 36 completed!")

Dataset saved: day36_model_ready_dataset.csv
Final shape: (3, 4)
Day 36 completed!

In [14]:
from pathlib import Path
import pandas as pd

file = Path("day36_model_ready_dataset.csv")

if file.exists():
    check_df = pd.read_csv(file)
    print("Dataset verified successfully!")
    print("Shape:", check_df.shape)
    display(check_df.head())
else:
    print("File not found. Run Cell 7 again.")

Dataset verified successfully!
Shape: (3, 4)

   study_hours  attendance  previous_score  assignments_completed
0          6.4        91.0            57.6                   8.71
1          4.2        85.5            37.8                   8.82
2          4.8        87.0            43.2                   8.51

In [15]:
print("Project: Student Performance Prediction System")
print("Day: 36")
print("Dataset Records:", len(df))
print("Dataset Features:", len(df.columns))
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Model Readiness Check Completed!")

Project: Student Performance Prediction System
Day: 36
Dataset Records: 3
Dataset Features: 4
Missing Values: 0
Duplicate Rows: 0
Model Readiness Check Completed!